default_ecosystem: ethereum

networks:
  custom:
     - name: ganache                  # Required
       chain_id: 1337                  # Required
       ecosystem: ethereum            # The ecosystem name, can either be new or an existing
       base_ecosystem_plugin: ethereum  # The ecosystem base-class, defaults to the default ecosystem

node:
  ethereum:
    ganache:
      uri: http://127.0.0.1:7545


ethereum:
  default_network: mainnet-fork
  mainnet:
    default_provider: infura
  mainnet_fork:
    default_provider: ganache

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5

plugins:
  - name: alchemy
    version: 0.8.0
  - name: arbitrum
    version: 0.8.0
  - name: avalanche
    version: 0.8.0
  - name: base
    version: 0.8.0
  - name: blast
    version: 0.8.0
  - name: bsc
    version: 0.8.0
  - name: ens
    version: 0.8.0
  - name: etherscan
    version: 0.8.0
  - name: fantom
    version: 0.8.0
  - name: infura
    version: 0.8.0
  - name: optimism
    version: 0.8.0
  - name: polygon
    version: 0.8.0
  - name: polygon-zkevm
    version: 0.8.0
  - name: solidity
    version: 0.8.2
  - name: tokens
    version: 0.8.0

console:
  plugins:
    - autoreload

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.1
  - name: openzeppelin-upgradeable
    github: OpenZeppelin/openzeppelin-contracts-upgradeable
    version: 4.8.1

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.1"
    - "@openzeppelin/contracts-upgradeable=openzeppelin-upgradeable/v4.8.1"
